### PR TITLE
Newly generated UIDs on export are made persistent

### PR DESCRIPTION
**Pull request by fhaftmann**
I am using calendar-import-export to have a purely local calendar solution over MTP only, with 3-way-merge of diverging calendars on my desktop and on my smartphone.

An issue in Android is that newly created calendar entries carry no UID for ical by default (I am using Etar on top of Offline Calendar). As I found it, calendar-import-export creates those ad-hoc: they are in the exported ical but with no backlink to the local calendar, which means that you can never re-import those in a valid way since they will always emerge as duplicates.

One solution is in this pull request: if UIDs have to be created, store them in the originating calendar entries.

The pull request is intended as a base for discussion and surely can be improved. One e. g. could argue that changing entries by just exporting them is not what a user expects; hence you could think about a setting which allows you to turn on and off that behaviour. Or to choose between not exporting entries with no UID at all or adding them on-the-fly.

I am  looking forward to your feedback.

### CODE REVIEW

**Comment by dschuermann** [comment]
This project is currently unmaintained. You solution sounds correct but I don't have a lot of time at hand to look into it and give proper feedback.

@jgriffiths worked a lot on it 2 years back. But I suspect he is also no longer invested.

@fhaftmann I can give you direct access to this repo so you could take over maintaining if you like.

**Comment by jgriffiths** [comment]
@dschuermann I'm still interested but my workload for the last couple of years hasn't allowed contributing. I'd like to remain a maintainer in case that changes in the future.

**Comment by dschuermann** [comment]
@jgriffiths Cool, that's great.

**Comment by jgriffiths** [comment]
@fhaftmann thanks!

**Comment by fhaftmann** [comment]
The generation of UIDs had a serious flaw that produced duplicated UIDs. This has been repaired.

**Comment by igor-cali** [comment]
@dschuermann if additional maintainers are needed, maybe I could help doing it.

**Comment by dschuermann** [comment]
@igor-cali sure, please start with testing this pull request and giving feedback.

**Comment by igor-cali** [comment]
@dschuermann
### Tested on AVD.

Test path:
1. Created a local calendar (with **Offline Calendar** app);
1. Created 3 events in the local calendar (one of them is full day);
1. Exported the calendar --> OK
1. Deleted all events from the local calendar;
1. Imported the events from the `*.ics` file made at point 3 --> OK, events are as previously created.

The UID's are created in this form:
```
[...]
BEGIN:VEVENT
DTSTAMP:20191109T125614Z
UID:15733040697920825c7f722f7442a8bf1a68a230ec881@sufficientlysecure.org
SUMMARY:Test
DTSTART;TZID=Europe/Rome:20191109T140000
DTEND:20191109T140000Z
END:VEVENT
[...]
```

**Comment by dschuermann** [comment]
@igor-cali What if you skip step 4? Are they properly detected as dublicates?

**Comment by igor-cali** [comment]
@dschuermann not completely: the events are not duplicated into the calendar, but the toast reports 0 dupes.

Screenshot_1573326617

**Comment by dschuermann** [comment]
Looks good to me. Though, the toast is confusing, but related to a different mechanism.

@igor-cali If you like to help, you can easily contribute for now with pull requests. There are enough issues to work on and the UI definitely needs an overhaul.

**Pull request merged**
