### PR TITLE
Minor bug correction

### PR DESCRIPTION
**Pull request by freddupont**
Hi, Ok it's my first time pulling a request, however I think this could help your project.

I'am from france and my objective is to make a soft able to import from ICS file in my calandar on daily bases from mail while removing all previous entry.

I found your open source soft and it do almost the job, great job by the way and thanks for sharing

I made the following change in this commit
store PREF_CALENDAR in setting so that you dont have to choose it every time
add a buttong clear, which erase all event
change the intent VIEW management on ICS file, by storing the Uri (storing URL string does not work on my phone).
Set all button to visible (for debug maybe you should not accept this)

tomorow I plan to change the UI in order to display more information on the ICS file
and add a clear_reminder button

Frederic

### CODE REVIEW

**Comment by dschuermann** [comment]
It's really difficult to see what you actually changed, because you moved lines around and reformatted stuff. Also, you removed functionality by commenting it out, I don't quite get what your intention is. Are you breaking old functionality?

If you want to contribute, please open single pull requests for features without breaking the already existing methods.

**Comment by freddupont** [comment]
As I said I am not used to modifiyng code, I will try to do what you said.At the end the only feature I break Is deleting entry corresponding to ICS file (do you realy need that?)
regards

 

    Le Dimanche 17 janvier 2016 22h15, Dominik Schürmann <notifications@github.com> a écrit :
 

 It's really difficult to see what you actually changed, because you moved lines around and reformatted stuff. Also, you removed functionality by commenting it out, I don't quite get what your intention is. Are you breaking old functionality?If you want to contribute, please open single pull requests for features without breaking the already existing methods.—

**Comment by jgriffiths** [comment]
Hi @freddupont, thanks for your contribution. I have to second what @dschuermann says, it is not possible to properly review your changes at present, although there are some issues that can be noted.

Any change you wish to submit should ideally be self contained, minimal and have a single purpose listed in the commit message.

Self contained means that the change should be able to applied alone. There is usually no point in splitting a change into multiple commits unless it is for clarity - such as splitting out refactoring or formatting from functional changes to make review easier. After applying a change, the code should still build and function correctly, any tests should pass, etc.

Having a single purpose means to change one thing at a time. This is easier to review and easier to select a subset of changes in the event that not all of them are wanted. So for example changing the application name and removing the load button in a single commit is not helpful, since we certainly don't want to change the application name in this repo.

Minimal means to avoid changes that are not strictly required. If you want to reformat the source code then do it in a different commit just for that purpose rather than mixing it in with functional changes. Formatting-only changes are unlikely to be accepted to many projects though. Things like swapping the order of xml elements for no reason make your real changes harder to see and so harder to review and less likely to be pulled.

**Comment by freddupont** [comment]
Thanks for the explanation.I create a new branch and I made a smallest commit, please tell me if this is what you expect.
regard
 

    Le Mardi 19 janvier 2016 2h35, jgriffiths <notifications@github.com> a écrit :
 

 Hi @freddupont, thanks for your contribution. I have to second what @dschuermann says, it is not possible to properly review your changes at present, although there are some issues that can be noted.Any change you wish to submit should ideally be self contained, minimal and have a single purpose listed in the commit message.Self contained means that the change should be able to applied alone. There is usually no point in splitting a change into multiple commits unless it is for clarity - such as splitting out refactoring or formatting from functional changes to make review easier. After applying a change, the code should still build and function correctly, any tests should pass, etc.Having a single purpose means to change one thing at a time. This is easier to review and easier to select a subset of changes in the event that not all of them are wanted. So for example changing the application name and removing the load button in a single commit is not helpful, since we certainly don't want to change the application name in this repo.Minimal means to avoid changes that are not strictly required. If you want to reformat the source code then do it in a different commit just for that purpose rather than mixing it in with functional changes. Formatting-only changes are unlikely to be accepted to many projects though. Things like swapping the order of xml elements for no reason make your real changes harder to see and so harder to review and less likely to be pulled.—

**Pull request closed without merging**
