### PR TITLE
Fix all day events

### LINKED ISSUE #50: [bug] Appointments over multiple day shrink to one day
This is the problem:
I exported an calendar with appointments that span over multiple days. Some of them have date+time for beginning and end. Others are define to be on from day x to y (complete day).
While the appointments with date+time stay spanned over multiple days, the other ones that are defined for the complete days are shrunk down to the first day.

Example:
LAN-Party
from 15.07.2016 10:00
to 17.07.2016 18:00

becomes:
BEGIN:VEVENT
...
SUMMARY:LAN-Party
ORGANIZER:mailto:me@owncloud.local
LOCATION:Somewhere
STATUS:CONFIRMED
DTSTART;TZID=Europe/Berlin:20160114T100000
DTEND:20160717T180000Z
END:VEVENT

4 days of Filming
from 25.07.2016
to 28.07.2016

becomes:
BEGIN:VEVENT
...
SUMMARY:4 days of Filming
ORGANIZER:mailto:me@owncloud.local
LOCATION:Somewhere
STATUS:CONFIRMED
DTSTART;VALUE=DATE:20160725
DTEND;VALUE=DATE:20160726
END:VEVENT

Version is 2.3
on Android 4.4.3

### PR DESCRIPTION
**Pull request by tasn**
There were issues with both all day event export and import.
These two patches solve both issues and all day events now work for me as expected.

This fixes #50

### CODE REVIEW

**Comment by dschuermann** [comment]
@tasn Thanks for this contribution.

@jgriffiths can you look into this?

**Comment by jgriffiths** [comment]
@tasn @dschuermann Hi, looks good to me provided the tests still pass. I added that special casing for a reason, but I cant recall what that was now, and I wont be able to check until next month at the earliest.

**Comment by tasn** [comment]
I haven't ran the tests (I assumed there'd be CI), though it works for me,
and the special cases were forcing one day to work around a bug that looked
like it was introduced by the mishandling of the export.

Let me know if you need anything.

**Comment by jgriffiths** [comment]
Thanks @tasn, the tests have to be run manually, I will hopefully get some time to look at outstanding stuff when I get a break.

**Comment by dschuermann** [comment]
@jgriffiths Just gently pinging you on this PR 😬

**Comment by dschuermann** [comment]
Works for me :)

**Pull request merged**
